id: IB4F5F7E7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T17:25:13+00:00'
last_modified: '2022-06-10T11:25:50.317958+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25861
  title: ཡུལ་མདོ་སྨད་ཀྱི་སྲིད་པའི་ཡུལ་ལྷ་གཞི་བདག་གི་བྱུང་བ་བརྗོད་པའི་དེབ་ཐེར་ཁྲ་བོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    420E:
      image_group_id: I1KG25863
      title: ''
      total_pages: 544
      order: 1
      base_file: 420E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
